name: Rebuild State Metrics

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/**'
      - 'build_metrics.py'
      - '.github/workflows/build_metrics.yml'

jobs:
  build-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push back changes

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List repo files
        run: ls -R
      - name: Run metrics script
        run: python build_sales_metrics.py

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state_metrics.json
          git commit -m "Update state_metrics.json" || echo "No changes to commit"
          git push
