name: Daily Data Update

on:
  schedule:
    - cron: "0 14 * * *"  # Covers 10 AM EDT
    - cron: "0 15 * * *"  # Covers 10 AM EST
  workflow_dispatch:      # allows manual trigger from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data download + processing script
        env:
          HUBSPOT_ACCESS_TOKEN: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
        run: |
          echo "$GOOGLE_TOKEN_JSON" > token.json
          python download_and_process.py
      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state_metrics.json
          git diff --cached --quiet || git commit -m "Update state metrics JSON"
          git push

